---
title: "Relapse data RUMC analysis"
author: "Sanne Post"
date: "3/7/2022"
output: html_document
---

```{r setup, include=FALSE}
library("readxl")
library(tidyr)
library(dplyr)
library(arsenal)
library(knitr)
library(VennDiagram)
library(stringr)
library("writexl")
knitr::opts_chunk$set(echo = TRUE)
```

# REPLASE data RUMC analysis

## Genes found in RUMC analysis, percentage patients have this mutation, top 20 mutations 
```{r cars}
all_genenamesR1 <- read.delim("//home//sanne//bioinf//afstuderen//DATA//RUMC//CASES//R1//CASENAME//AllCasesR1.csv", sep = ",")

# all_genenames <- subset(all_genenames, !(Gene.name %in% c("IGHA1","IGHE","IGHG1","IGHG2","IGHG4","IGHJ1","IGHJ3","IGHJ5","IGHMBP2","IGHV1-69","IGHV2-70D","IGHV3-23","IGHV3-48","IGHV4-34")))

genes_casesR1 <- all_genenamesR1 %>%
  select(Gene.name, FILENAME)

genes_casesR1 <- genes_casesR1[!grepl("IGH", genes_casesR1$Gene.name),]
genes_casesR1 <- genes_casesR1[!grepl("IGK", genes_casesR1$Gene.name),]
genes_casesR1 <- genes_casesR1[!grepl("IGL", genes_casesR1$Gene.name),]

genesAndFileOrderdR1 <- genes_casesR1 %>% count(Gene.name, FILENAME)
genesOrderdR1 <- genesAndFileOrderdR1 %>% count(Gene.name)

newheaders <- c("gene",	"amount_patients")
colnames(genesOrderdR1) <- newheaders

genesOrderdR1 %>% 
    arrange(desc(amount_patients)) %>%
    slice(1:20) %>%
    ggplot(., aes(x=gene, y=amount_patients))+
              geom_bar(stat='identity') +
              theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
              ggtitle("Top 20 most found genes")

percent <- function(x, digits = 2, format = "f", ...) {      # Create user-defined function
  paste0(formatC(x * 10, format = format, digits = digits, ...), "%")
}

genesOrderdPercentR1 <- genesOrderdR1
genesOrderdPercentR1$percentage <- (genesOrderdPercentR1$amount_patients/10)*100

newheaders <- c("gene",	"amount_patients" , "percentage")
colnames(genesOrderdPercentR1) <- newheaders

genesOrderdPercentR1 %>% 
    arrange(desc(percentage)) %>%
    slice(1:20) %>%
    ggplot(., aes(x=gene, y=percentage))+
              geom_bar(stat='identity') +
              theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
              ggtitle("Top 20 most found genes")
```

## Genes RUMC also found by the chapuy study

```{r}
chapuy_CCG <- read.delim("//home//sanne//bioinf//afstuderen//DATA//chapuy//CCG_Chapuy.csv")

chapuyRUMCR1 <- generics::intersect(chapuy_CCG$gene, genesOrderdR1$gene)  # Apply intersect function
chapuyRUMCR1

chapuy_RUMC_genes_overlapR1 <- chapuy_CCG %>% filter_all(any_vars(. %in% chapuyRUMCR1))
```

## Gene and percentages chapuy CCG genes

```{r}
chapuy_CCG_percentage <- chapuy_CCG
chapuy_CCG_percentage$percentage <- (chapuy_CCG_percentage$npat/304)*100

chapuy_CCG_percentage %>% 
    arrange(desc(percentage)) %>%
    slice(1:50) %>%
    ggplot(., aes(x=gene, y=percentage))+
              geom_bar(stat='identity') +
              theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
              ggtitle("Top 50 most found genes")

chapuyRUMC_percentageR1 <- generics::intersect(chapuy_CCG_percentage$gene, genesOrderdR1$gene)  # Apply intersect function
chapuyRUMC_percentageR1

chapuy_RUMC_genes_overlap_percentageR1 <- chapuy_CCG_percentage %>% filter_all(any_vars(. %in% chapuyRUMC_percentageR1))
```

## Genes RUMC also found by the schmitz study
```{r}
Schmitz <- read.delim("//home//sanne//bioinf//afstuderen//DATA//Schmitz//GeneticPredictors.csv", header = TRUE)
#data <- read.table("data.txt", skip = 2, header = FALSE)
#unique(Schmitz)
SchmitzRUMCR1 <- generics::intersect(Schmitz$Gene.symbol, genesOrderdR1$gene)  # Apply intersect function
SchmitzRUMCR1

Schmitz_RUMC_genes_overlapR1 <- Schmitz %>% filter_all(any_vars(. %in% SchmitzRUMCR1))
```

## Write
```{r}
# write_xlsx(genesOrderdPercentR1,"//home//sanne//bioinf//afstuderen//ANALYSIS//LITvsDATA//GenesPercentageRelapse.xlsx")
# write_xlsx(chapuy_RUMC_genes_overlap_percentageR1,"//home//sanne//bioinf//afstuderen//ANALYSIS//LITvsDATA//RUMCvsCHAPUYrelapse.xlsx")
# write_xlsx(Schmitz_RUMC_genes_overlapR1,"//home//sanne//bioinf//afstuderen//ANALYSIS//LITvsDATA//RUMCvsSCHMITZrelapse.xlsx")
write_xlsx(chapuy_CCG_percentage,"//home//sanne//bioinf//afstuderen//ANALYSIS//LITvsDATA//CHAPUY_CCGpercentage.xlsx")

```